---
- name: "Display Mikrotik Status"
  hosts: mikrotiks
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Display OS version
      routeros_command:
        commands: "/system package print"
      register: os_version
    - name: Display OS version
      debug: var=os_version['stdout_lines']

    - name: Display firmware version
      routeros_command:
        commands: "/system routerboard print"
      register: firmware_version
    - name: Display OS version
      debug: var=firmware_version['stdout_lines']

    - name: Display list of files on device
      routeros_command:
        commands: "/file print"
      register: list_files
    - name: Display list of files on device
      debug: var=list_files['stdout_lines']